Repository droztech/droz-visu, pull requests merged in 2024-04, with the labels that each got.

#146 chore: toast colors
  package-lock.json
  package/src/library/Toast/Root.tsx
Labels: chore

#147 release: 3.3.0
  docs/package.json
  package-lock.json
  package.json
  package/package.json
Labels: skip-changelog

#148 Chore small changes
  docs/package.json
  package-lock.json
  package.json
  package/package.json
  package/src/library/Select/Item.tsx
  package/src/library/Sidebar/Button.tsx
Labels: chore

#153 Feat calendar
  .github/pull_request_template.md
  docs/src/stories/Calendar/Calendar.stories.tsx
  package-lock.json
  package/package.json
  package/src/App.tsx
  package/src/__tests__/Calendar/Calendar.test.tsx
  package/src/library/Calendar/index.tsx
  package/src/library/Popover/Content.tsx
  package/src/library/Select/Root.tsx
  package/src/library/index.ts
Labels: feature

#156 feat: table
  docs/src/stories/Table/Root.stories.tsx
  docs/src/stories/Table/Row.stories.tsx
  package-lock.json
  package/src/App.tsx
  package/src/__tests__/Table/Body.test.tsx
  package/src/__tests__/Table/Caption.test.tsx
  package/src/__tests__/Table/Cell.test.tsx
  package/src/__tests__/Table/Head.test.tsx
  package/src/__tests__/Table/Header.test.tsx
  package/src/__tests__/Table/Root.test.tsx
  package/src/__tests__/Table/Row.test.tsx
  package/src/library/Chip/Root.tsx
  package/src/library/Form/index.ts
  package/src/library/Pagination/index.tsx
  package/src/library/Table/Body.tsx
  package/src/library/Table/Caption.tsx
  package/src/library/Table/Cell.tsx
  package/src/library/Table/Head.tsx
  package/src/library/Table/Header.tsx
  package/src/library/Table/Root.tsx
  package/src/library/Table/Row.tsx
  package/src/library/Table/index.ts
  package/src/library/index.ts
Labels: feature

#155 DatePicker component creation
  docs/src/stories/DatePicker/DatePicker.stories.tsx
  package/src/App.tsx
  package/src/__tests__/DatePicker/DatePicker.test.tsx
  package/src/library/DatePicker/index.tsx
  package/src/library/index.ts
Labels: feature

#160 Update DatePicker Component Width Based on Internal Popover
  package/src/App.tsx
  package/src/library/DatePicker/index.tsx
  package/src/library/Popover/Content.tsx
Labels: bugfix

#162 maledeto datepicker
  package/src/library/DatePicker/index.tsx
Labels: bugfix
