Repository droztech/droz-visu, pull requests merged in 2024-03, with the labels that each got.

#129 chore: variant example
  package-lock.json
  package/src/library/Avatar/index.tsx
  package/src/library/Button/index.tsx
  package/src/library/Checkbox/index.tsx
  package/src/library/Dialog/Footer.tsx
  package/src/library/Dialog/index.ts
  package/src/library/Divider/index.tsx
  package/src/library/Icon/index.tsx
  package/src/library/Input/Root.tsx
  package/src/library/Link/index.tsx
  package/src/library/Loading/index.tsx
  package/src/library/Menu/Root.tsx
  package/src/library/Radio/Item.tsx
  package/src/library/Select/Root.tsx
  package/src/library/Toast/Provider/index.tsx
  package/src/library/Toast/Root.tsx
  package/src/library/types/index.ts
Labels: chore

#130 Chore libs update
  README.md
  docs/README.md
  docs/package.json
  docs/public/droz-visu.svg
  docs/src/index.stories.mdx
  docs/src/stories/Accordion/Trigger.stories.tsx
  docs/src/stories/Avatar/Avatar.stories.tsx
  docs/src/stories/Button/Button.stories.tsx
  docs/src/stories/Checkbox/Checkbox.stories.tsx
  docs/src/stories/Dialog/Header.stories.tsx
  docs/src/stories/Dialog/Root.stories.tsx
  docs/src/stories/Divider/Divider.stories.tsx
  docs/src/stories/FloatCard/Content.stories.tsx
  docs/src/stories/FloatCard/Root.stories.tsx
  docs/src/stories/FloatCard/Trigger.stories.tsx
  docs/src/stories/Icon/Icon.stories.tsx
  docs/src/stories/Input/Icon.stories.tsx
  docs/src/stories/Input/Root.stories.tsx
  docs/src/stories/Menu/Body.stories.tsx
  docs/src/stories/Menu/Button.stories.tsx
  docs/src/stories/Sidebar/Body.stories.tsx
  docs/src/stories/Sidebar/Button.stories.tsx
  docs/src/stories/Sidebar/Header.stories.tsx
  docs/src/stories/Tabs/Content.stories.tsx
  docs/src/stories/Tabs/List.stories.tsx
  docs/src/stories/Tabs/Root.stories.tsx
  docs/src/stories/Tabs/Trigger.stories.tsx
  docs/src/stories/Toggle/Item.stories.tsx
  docs/src/stories/Toggle/Toggle.stories.tsx
  docs/src/stories/Tooltip/Close.stories.tsx
  docs/src/stories/Tooltip/Hover.stories.tsx
  docs/src/stories/Tooltip/Step.stories.tsx
  package-lock.json
  package.json
  package/README.md
  package/package.json
  package/public/design-visu.svg
  package/public/droz-visu.svg
  package/src/App.tsx
  package/src/__tests__/Dialog/Header.test.tsx
  package/src/__tests__/Icon/Icon.test.tsx
  package/src/__tests__/Input/Icon.test.tsx
  package/src/__tests__/Input/Root.test.tsx
  package/src/__tests__/Menu/Button.test.tsx
  package/src/__tests__/Sidebar/Button.test.tsx
  package/src/__tests__/Tabs/Root.test.tsx
  package/src/__tests__/Tabs/Trigger.test.tsx
  package/src/layout/Default.tsx
  package/src/library/Accordion/Trigger.tsx
  package/src/library/Checkbox/index.tsx
  package/src/library/Dialog/Header.tsx
  package/src/library/File/index.tsx
  package/src/library/Select/Root.tsx
  package/src/library/Sidebar/Root.tsx
  package/src/library/Toast/Root.tsx
  package/src/library/Tooltip/Close.tsx
  package/src/library/Tooltip/Step.tsx
  package/vite.config.ts
  visu.svg
Labels: chore

#131 Feat: added the option to have a search in the select component
  docs/src/stories/Select/Root.stories.tsx
  package/src/App.tsx
  package/src/__tests__/Select/Search.test.tsx
  package/src/library/Select/Root.tsx
  package/src/library/Select/Search.tsx
  package/src/library/Select/index.ts
Labels: feature

#133 Adjust collapsed sidebar component to show Avatar component
  package/src/App.tsx
  package/src/library/Select/Root.tsx
  package/src/library/Select/Search.tsx
  package/src/library/Sidebar/Body.tsx
  package/src/library/Sidebar/Button.tsx
  package/src/library/Sidebar/Root.tsx
Labels: feature

#134 Feat form
  docs/src/stories/Form/Group.stories.tsx
  docs/src/stories/Form/Label.stories.tsx
  docs/src/stories/Form/Message.stories.tsx
  docs/src/stories/Form/Root.stories.tsx
  package-lock.json
  package/src/App.tsx
  package/src/__tests__/Form/Group.test.tsx
  package/src/__tests__/Form/Label.test.tsx
  package/src/__tests__/Form/Message.test.tsx
  package/src/__tests__/Form/Root.test.tsx
  package/src/library/Form/Group.tsx
  package/src/library/Form/Label.tsx
  package/src/library/Form/Message.tsx
  package/src/library/Form/Root.tsx
  package/src/library/Form/index.tsx
  package/src/library/index.ts
Labels: feature

#136 Bug - Adjust css side spacing in collapsed sidebar
  package/src/library/Sidebar/Body.tsx
  package/src/library/Sidebar/Button.tsx
  package/src/library/Sidebar/Root.tsx
Labels: chore

#138 fix: toggle styles
  package-lock.json
  package/src/App.tsx
  package/src/library/Toggle/Item.tsx
Labels: bugfix

#139 Release 3.1.1
  README.md
  docs/package.json
  package-lock.json
  package.json
  package/package.json
Labels: skip-changelog

#141 fix: form group type
  package/src/library/Form/Label.tsx
Labels: chore

#140 Popover frontend component creation
  docs/src/stories/Popover/Content.stories.tsx
  docs/src/stories/Popover/Root.Stories.tsx
  docs/src/stories/Popover/Trigger.stories.tsx
  package/src/App.tsx
  package/src/__tests__/Popover/Content.test.tsx
  package/src/__tests__/Popover/Root.test.tsx
  package/src/__tests__/Popover/Trigger.test.tsx
  package/src/library/Popover/Content.tsx
  package/src/library/Popover/Root.tsx
  package/src/library/Popover/Trigger.tsx
  package/src/library/Popover/index.ts
  package/src/library/index.ts
Labels: feature

#142 release: 3.2.0
  docs/package.json
  package-lock.json
  package.json
  package/package.json
Labels: skip-changelog
